# Generated by Django 3.2.8 on 2021-10-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('center_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('contents_text', models.TextField(verbose_name='본문')),
                ('created_at', models.DateTimeField(verbose_name='작성일')),
                ('created_by', models.CharField(max_length=100, verbose_name='작성자')),
                ('is_view', models.BooleanField(default=True, verbose_name='공개 여부')),
            ],
        ),
    ]
