# Generated by Django 3.2.7 on 2021-10-17 07:08

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('cases', '0003_case_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='modify_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='MODIFY DATE'),
        ),
        migrations.AlterField(
            model_name='case',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
