# Generated by Django 3.2.7 on 2021-10-23 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_auto_20211017_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='keyword1',
        ),
    ]
