# Generated by Django 3.2.7 on 2021-11-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='contents_text',
        ),
        migrations.AddField(
            model_name='case',
            name='contents_text1',
            field=models.TextField(blank=True, null=True, verbose_name='본문'),
        ),
        migrations.AddField(
            model_name='case',
            name='contents_text2',
            field=models.TextField(blank=True, null=True, verbose_name='본문'),
        ),
        migrations.AddField(
            model_name='case',
            name='sub_title1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='제목'),
        ),
        migrations.AddField(
            model_name='case',
            name='sub_title2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='제목'),
        ),
    ]
