# Generated by Django 3.2.7 on 2021-11-06 09:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_auto_20211106_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='description',
            field=ckeditor.fields.RichTextField(default=True, null=True),
        ),
    ]
