# Generated by Django 3.2.7 on 2021-11-06 09:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_case_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='contents_text1',
            field=ckeditor.fields.RichTextField(default=True, null=True, verbose_name='본문'),
        ),
    ]
