# Generated by Django 3.2.7 on 2021-11-06 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_alter_case_contents_text1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='contents_text1',
            new_name='contents_text',
        ),
        migrations.RemoveField(
            model_name='case',
            name='contents_text2',
        ),
        migrations.RemoveField(
            model_name='case',
            name='sub_title1',
        ),
        migrations.RemoveField(
            model_name='case',
            name='sub_title2',
        ),
    ]
