# Generated by Django 3.2.7 on 2021-11-06 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_auto_20211106_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='description',
        ),
    ]
