# Generated by Django 3.2.7 on 2021-11-06 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_remove_case_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='center_image',
        ),
    ]
